sudo: required
language: java
cache:
  directories:
  - $HOME/.m2/repository/
jdk:
  - openjdk8
script:
- mvn clean
deploy:
# deploy develop to the staging environment
  - provider: script
    script: mvn -s .m2/settings.xml clean source:jar deploy -Dmaven.test.skip -Dgithub-token=${api_token} -Pgithub
    on:
      tags: true
    # deploy master to production
  - provider: script
    script: mvn -s .m2/settings.xml clean source:jar deploy -Dmaven.test.skip -Dgithub-token=${api_token} -Pgithub
    on:
      branch: develop