# 测试
sudo: required
language: java
cache:
  directories:
  - $HOME/.m2/repository/
  - $HOME/.m2/project/
# 仓库的分支
branches:
  only:
  - develop
  - feature/*
  - tags
jdk:
- oraclejdk8
install:
- mvn clean source:jar deploy -Dmaven.test.skip -Dgithub-token=${api_token}
script:
- ls