sudo: required
language: java
cache:
  directories:
  - $HOME/.m2/repository/
# 仓库的分支
branches:
  only:
  - develop
  - feature/*
  - tags
jdk:
  - oraclejdk8
script:
- mvn clean source:jar deploy -Dmaven.test.skip -Dgithub-token=${api_token} -Pgithub
