name: Java CI

on:
  push:
    branches:
    - develop
    - feature/*

jobs:
  publish:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8.0.292'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean deploy -Dmaven.test.skip
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_PASS }}